### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by chinnikrishna55** [matan2050/TFMatcher#1]
Getting following error

Undefined function or variable 'TfValue'.

Error in TfDistance (line 26)
    difference = difference + ((TfValue(tfL,xEventOrder(i)) - ...

Error in demo (line 14)
shapeDifference_square2square   = TfDistance(tfSquare1, tfSquare2);

**Comment by matan2050** [comment]
yes, apparently there is a file missing,
I'll look for it and push the appropriate changes.

**Comment by matan2050** [comment]
uploaded the missing file, you may check it if you can, I no longer have access to Matlab

**Comment by matan2050** [comment]
@chinnikrishna55 ,
uploaded the missing file, you may check if it works, I no longer have access to Matlab
